version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      # バックエンドのビルド
      - cd backend && mvn package
      # 設定ファイルの準備
      - cp config/prod.conf dist/config/

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - dist/**/*
    - backend/target/*.jar
    - config/**/*
  discard-paths: no  # パス構造を維持
