# Generated by Django 3.2.13 on 2022-10-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sent_at',
            field=models.BooleanField(default=False),
        ),
    ]
